// Copyright Vessel contributors. Licensed under Apache-2.0. See LICENSE.

#include "Session/VesselRejectionSink.h"

#include "VesselLog.h"

#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformFileManager.h"
#include "GenericPlatform/GenericPlatformFile.h"
#include "Misc/DateTime.h"
#include "Misc/FileHelper.h"
#include "Misc/Paths.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "Policies/CondensedJsonPrintPolicy.h"

namespace VesselRejectionSinkDetail
{
	static const TCHAR* kRejectionsHeader = TEXT("## Known Rejections");
	static const TCHAR* kAutoManagedNote  = TEXT("<!-- auto-managed by Vessel HITL Gate — see HITL_PROTOCOL.md §4.2 -->");

	/** Extract a shallow "target" hint from ArgsJson. Best-effort. */
	static FString InferTarget(const FString& ArgsJson)
	{
		TSharedPtr<FJsonObject> Obj;
		TSharedRef<TJsonReader<TCHAR>> Reader = TJsonReaderFactory<TCHAR>::Create(ArgsJson);
		if (!FJsonSerializer::Deserialize(Reader, Obj) || !Obj.IsValid())
		{
			return FString();
		}
		// Most tools accept AssetPath or ContentPath; try those in order.
		FString V;
		if (Obj->TryGetStringField(TEXT("AssetPath"),   V) && !V.IsEmpty()) return V;
		if (Obj->TryGetStringField(TEXT("ContentPath"), V) && !V.IsEmpty()) return V;
		if (Obj->TryGetStringField(TEXT("Path"),        V) && !V.IsEmpty()) return V;
		return FString();
	}
}

FString FVesselRejectionSink::GetAgentsMdPath()
{
	return FPaths::ConvertRelativePathToFull(FPaths::ProjectDir() / TEXT("AGENTS.md"));
}

FString FVesselRejectionSink::GetArchivePathForMonth(const FDateTime& UtcNow)
{
	const FString Dir = FPaths::ProjectSavedDir() / TEXT("VesselRejectionArchive");
	const FString FileName = FString::Printf(TEXT("%04d-%02d.jsonl"),
		UtcNow.GetYear(), UtcNow.GetMonth());
	return FPaths::ConvertRelativePathToFull(Dir / FileName);
}

bool FVesselRejectionSink::AgentsMdHasRejectionsSection(const FString& Contents)
{
	return Contents.Contains(VesselRejectionSinkDetail::kRejectionsHeader, ESearchCase::CaseSensitive);
}

FString FVesselRejectionSink::FormatAgentsMdEntry(
	const FVesselApprovalRequest& Request,
	const FVesselApprovalDecision& Decision)
{
	const FString Ts     = FDateTime::UtcNow().ToIso8601();
	const FString Target = VesselRejectionSinkDetail::InferTarget(Request.ArgsJson);
	const FString Tool   = Request.ToolName.ToString();

	FString Out;
	Out += FString::Printf(TEXT("\n### %s · tool=%s%s\n"),
		*Ts, *Tool,
		Target.IsEmpty() ? TEXT("") : *FString::Printf(TEXT(" · target=%s"), *Target));
	Out += FString::Printf(TEXT("**reason**: %s\n"), *Decision.RejectReason);
	Out += FString::Printf(TEXT("**session**: %s, step %d\n"), *Request.SessionId, Request.StepIndex);
	Out += FString::Printf(TEXT("**rejecter**: %s\n"),
		Decision.DeciderId.IsEmpty() ? TEXT("unknown") : *Decision.DeciderId);
	return Out;
}

bool FVesselRejectionSink::AppendToAgentsMd(
	const FVesselApprovalRequest& Request,
	const FVesselApprovalDecision& Decision)
{
	const FString Path = GetAgentsMdPath();
	FString Existing;
	const bool bExists = FFileHelper::LoadFileToString(Existing, *Path);

	if (!bExists || Existing.IsEmpty())
	{
		// First-time creation — lay out the minimal header so the file reads well.
		FString Created;
		Created += TEXT("# AGENTS.md\n\n");
		Created += TEXT("Auto-generated by Vessel on first reject. You can edit the text above this line; ");
		Created += TEXT("content under the Known Rejections header is managed by the HITL Gate.\n\n");
		Created += VesselRejectionSinkDetail::kRejectionsHeader;
		Created += TEXT("\n");
		Created += VesselRejectionSinkDetail::kAutoManagedNote;
		Created += TEXT("\n");
		Created += FormatAgentsMdEntry(Request, Decision);
		return FFileHelper::SaveStringToFile(Created, *Path);
	}

	FString NewContents = Existing;
	if (!AgentsMdHasRejectionsSection(NewContents))
	{
		NewContents += TEXT("\n\n");
		NewContents += VesselRejectionSinkDetail::kRejectionsHeader;
		NewContents += TEXT("\n");
		NewContents += VesselRejectionSinkDetail::kAutoManagedNote;
		NewContents += TEXT("\n");
	}
	NewContents += FormatAgentsMdEntry(Request, Decision);

	if (!FFileHelper::SaveStringToFile(NewContents, *Path))
	{
		UE_LOG(LogVesselHITL, Warning, TEXT("Failed to write AGENTS.md at '%s'"), *Path);
		return false;
	}
	return true;
}

bool FVesselRejectionSink::AppendToArchive(
	const FVesselApprovalRequest& Request,
	const FVesselApprovalDecision& Decision)
{
	const FDateTime Now = FDateTime::UtcNow();
	const FString Path = GetArchivePathForMonth(Now);
	IFileManager::Get().MakeDirectory(*FPaths::GetPath(Path), /*Tree=*/true);

	TSharedRef<FJsonObject> Obj = MakeShared<FJsonObject>();
	Obj->SetStringField(TEXT("ts"),         Now.ToIso8601());
	Obj->SetStringField(TEXT("session"),    Request.SessionId);
	Obj->SetNumberField(TEXT("step_index"), Request.StepIndex);
	Obj->SetStringField(TEXT("tool"),       Request.ToolName.ToString());
	Obj->SetStringField(TEXT("category"),   Request.ToolCategory);
	Obj->SetStringField(TEXT("args_json"),  Request.ArgsJson);
	Obj->SetStringField(TEXT("reasoning"),  Request.Reasoning);
	Obj->SetStringField(TEXT("reason"),     Decision.RejectReason);
	Obj->SetStringField(TEXT("decider"),    Decision.DeciderId);

	FString Line;
	TSharedRef<TJsonWriter<TCHAR, TCondensedJsonPrintPolicy<TCHAR>>> Writer =
		TJsonWriterFactory<TCHAR, TCondensedJsonPrintPolicy<TCHAR>>::Create(&Line);
	FJsonSerializer::Serialize(Obj, Writer);
	Line.AppendChar(TEXT('\n'));

	IPlatformFile& PlatformFile = FPlatformFileManager::Get().GetPlatformFile();
	TUniquePtr<IFileHandle> Handle(PlatformFile.OpenWrite(
		*Path, /*bAppend=*/true, /*bAllowRead=*/true));
	if (!Handle)
	{
		UE_LOG(LogVesselHITL, Warning, TEXT("Failed to open archive file '%s'"), *Path);
		return false;
	}

	FTCHARToUTF8 Converter(*Line);
	Handle->Write(reinterpret_cast<const uint8*>(Converter.Get()),
		static_cast<int64>(Converter.Length()));
	Handle->Flush();
	return true;
}

bool FVesselRejectionSink::Record(
	const FVesselApprovalRequest& Request,
	const FVesselApprovalDecision& Decision)
{
	if (Decision.Kind != EVesselApprovalDecisionKind::Reject)
	{
		return false;
	}
	const bool bMd      = AppendToAgentsMd(Request, Decision);
	const bool bArchive = AppendToArchive(Request, Decision);
	return bMd || bArchive;
}
